dist: bionic
language: node_js
node_js:
  - "lts/*"
# before_script:
#   - npm link
#   - npm link await-fn
after_success:
  - npm install -g nyc coveralls
  - nyc npm test && nyc report --reporter=text-lcov | coveralls
